### ISSUE TITLE
base64デコードができなかった場合のエラーハンドリング

### ISSUE THREAD

**Issue by t3tra-dev** [mckomaken/Command-Lab-Official-Bot#11]
`cbase64.py`をなんとかする

**Comment by ap12-code** [comment]
#12  でハンドリング済み

**Comment by t3tra-dev** [comment]
ナイスです！！！
![アルティメット偉業](https://media.misskeyusercontent.jp/misskey/webpublic-36b00938-a4b3-4fcf-b2e5-edf14b6fd53e.png)
